### PR TITLE
Add note that repo has moved

### PR DESCRIPTION
**Pull request by tetchel**
Signed-off-by: Tim Etchells <tetchell@redhat.com>

### CODE REVIEW

**Review by lstocchi — APPROVED** [review]
LGTM

**Comment by jeffmaury** [comment]
We should also archive this repo once merged as it will make it clear that no more maintenance is performed

**Comment by lstocchi** [comment]
> We should also archive this repo once merged as it will make it clear that no more maintenance is performed

Yep, it's already planned :+1:

**Comment by jduimovich** [comment]
We should publish the replacement action into the marketplace, and remove the old one. We don't want users to find a deprecated action in the marketplace with no released alternative

**Pull request merged**
